site_name: Oles dokumentasjon
site_url: https://ol-e.github.io/docsv2/
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Hjem: index.md
  - Oppskrifter:
      - Pizza: oppskrifter/pizza.md
      - Pasta med pesto: oppskrifter/pasta-med-pesto.md
      - Enkel omelett: oppskrifter/enkel-omelett.md
      - Kyllingwrap: oppskrifter/kyllingwrap.md
      - Havregrøt: oppskrifter/havregrot.md
      - Fruktsalat: oppskrifter/fruktsalat.md
  - Google-guide: how_to_use_google.md
