site_name: Oles dokumentasjon
site_url: https://ol-e.github.io/docsv2/
theme:
  name: material
nav:
  - Hjem: index.md
  - Oppskrifter:
      - Pizza: Pizza.md
      - Kremet kyllingsuppe: Chicken_soup.md
  - Guider:
      - Hvordan bruke Google: how_to_use_google.md
      - Hvordan laste opp bilder: how_to_upload_pictures.md
